# -*- coding: utf-8 -*-
"""AiServer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qb_0C49jiMjvjU_hguSn0MynDrqJ0m_V
"""

# ✅ Step 1. 필수 패키지 설치 (중복 없이 한 번만)
!pip install scikit-learn==1.5.0 lightgbm fastapi uvicorn nest_asyncio pyngrok joblib optuna openai
!ngrok config add-authtoken 2wRlFfu3fZMabUEXJpLOYXQNbUK_3jakPRTomUDEKRj9FiHjB

# ✅ Step 2. 라이브러리 import
import os
import numpy as np
import pandas as pd
import joblib
import optuna
import threading
import uvicorn
import nest_asyncio
from fastapi import FastAPI, APIRouter, Query
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from pyngrok import ngrok
from lightgbm import LGBMClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
from openai import OpenAI
import json
from pydantic import BaseModel
from sklearn.cluster import KMeans
from collections import Counter
import random
from pydantic import BaseModel
from typing import List


# ✅ Colab 환경에서 중첩 이벤트 루프 허용
nest_asyncio.apply()

# ✅ FastAPI 앱 생성
app = FastAPI()

# ✅ CORS 허용 (모든 도메인에서 접근 가능하게)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ✅ 라우터 생성
router = APIRouter()

# ✅ OpenAI 클라이언트

client = OpenAI(api_key="")

"""운동추천 api

인기 운동 api
"""

# ✅ 1. 운동 클래스와 규칙 정의
classes = [
    "의자 스쿼트", "발끝 들기", "뒤꿈치 들기", "버드독", "벽 짚고 플랭크",
    "사이드 스텝", "서서 하는 트위스트", "스탠딩 사이드 레그 리프트",
    "스탠딩 힙 익스텐션", "싱글 레그 스탠딩", "어깨 스트레칭",
    "제자리 걷기", "종아리 스트레칭", "좌우 스탠딩 크런치", "허리 회전 스트레칭"
]

focus_area_map = {"하체": 0, "코어": 1, "전신": 2, "유연성": 3, "균형": 4}
label_rules = {
    "의자 스쿼트":            {"score": (40, 60), "age": (65, 80), "condition": 0, "focus": "하체"},
    "발끝 들기":             {"score": (30, 50), "age": (70, 80), "condition": 0, "focus": "하체"},
    "뒤꿈치 들기":           {"score": (40, 55), "age": (65, 80), "condition": 0, "focus": "하체"},
    "버드독":               {"score": (75, 90), "age": (50, 65), "condition": 2, "focus": "코어"},
    "벽 짚고 플랭크":        {"score": (80, 95), "age": (50, 60), "condition": 2, "focus": "코어"},
    "사이드 스텝":          {"score": (60, 80), "age": (55, 70), "condition": 1, "focus": "전신"},
    "서서 하는 트위스트":     {"score": (50, 70), "age": (60, 75), "condition": 1, "focus": "코어"},
    "스탠딩 사이드 레그 리프트": {"score": (45, 65), "age": (50, 70), "condition": 1, "focus": "하체"},
    "스탠딩 힙 익스텐션":     {"score": (45, 65), "age": (55, 75), "condition": 1, "focus": "하체"},
    "싱글 레그 스탠딩":       {"score": (85, 100), "age": (50, 60), "condition": 2, "focus": "균형"},
    "어깨 스트레칭":         {"score": (30, 50), "age": (65, 80), "condition": 0, "focus": "유연성"},
    "제자리 걷기":           {"score": (50, 65), "age": (60, 75), "condition": 1, "focus": "전신"},
    "종아리 스트레칭":       {"score": (40, 55), "age": (65, 80), "condition": 0, "focus": "유연성"},
    "좌우 스탠딩 크런치":     {"score": (55, 75), "age": (55, 70), "condition": 1, "focus": "코어"},
    "허리 회전 스트레칭":     {"score": (45, 65), "age": (65, 80), "condition": 0, "focus": "유연성"},
}

# ✅ 2. 데이터 생성
samples_per_class = 333
records = []
for label in classes:
    rule = label_rules[label]
    for _ in range(samples_per_class):
        left, right = np.random.randint(*rule["score"], size=2)
        age = np.random.randint(*rule["age"])
        gender = np.random.randint(0, 2)
        condition = rule["condition"]
        focus_area_code = focus_area_map[rule["focus"]]

        balance_diff = left - right
        recent_scores = [left + np.random.randint(-5, 5) for _ in range(3)]
        recent_avg = np.mean(recent_scores)
        recent_var = np.var(recent_scores)
        last_week_intensity = np.random.uniform(0.5, 1.0)
        last_week_duration = np.random.randint(20, 90)

        records.append([
            left, right, age, gender, condition,
            balance_diff, recent_avg, recent_var,
            last_week_intensity, last_week_duration,
            focus_area_code, label
        ])

data = pd.DataFrame(records, columns=[
    "balance_score_left", "balance_score_right", "age", "gender", "condition_encoded",
    "balance_diff", "recent_avg_score", "score_variance",
    "last_week_intensity", "last_week_duration", "focus_area_code", "label"
])

# ✅ 3. 라벨 인코딩 및 학습
le_label = LabelEncoder()
data["label_encoded"] = le_label.fit_transform(data["label"])
X = data.drop(columns=["label", "label_encoded"])
y = data["label_encoded"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

'''

# ✅ 4. Optuna 튜닝

def objective(trial):
    params = {
        "objective": "multiclass",
        "num_class": len(np.unique(y)),
        "metric": "multi_logloss",
        "verbosity": -1,
        "boosting_type": "gbdt",
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3),
        "num_leaves": trial.suggest_int("num_leaves", 20, 100),
        "max_depth": trial.suggest_int("max_depth", 3, 12),
        "min_child_samples": trial.suggest_int("min_child_samples", 10, 100),
        "min_gain_to_split": trial.suggest_float("min_gain_to_split", 0.0, 1.0),
        "subsample": trial.suggest_float("subsample", 0.6, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.6, 1.0),
        "n_estimators": trial.suggest_int("n_estimators", 100, 500),
    }
    model = LGBMClassifier(**params)
    model.fit(X_train, y_train)
    preds = model.predict(X_test)
    acc = accuracy_score(y_test, preds)
    print(f"Accuracy: {acc:.4f}")
    return acc

study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=10)

best_params = study.best_params
best_params["objective"] = "multiclass"
best_params["num_class"] = len(np.unique(y))
model = LGBMClassifier(**best_params)
model.fit(X_train, y_train)

joblib.dump(model, "lightgbm_best_model.pkl")
joblib.dump(le_label, "label_encoder.pkl")
'''
model = joblib.load("lightgbm_best_model.pkl")
le_label = joblib.load("label_encoder.pkl")
from sklearn.metrics import precision_score, recall_score, f1_score, classification_report, confusion_matrix

# 테스트셋 예측
y_pred = model.predict(X_test)

# 정확도
acc = accuracy_score(y_test, y_pred)
print(f"\n🎯 정확도 (Accuracy): {acc:.4f}")

# 정밀도, 재현율, F1
precision = precision_score(y_test, y_pred, average='macro', zero_division=0)
recall = recall_score(y_test, y_pred, average='macro', zero_division=0)
f1 = f1_score(y_test, y_pred, average='macro', zero_division=0)

print(f"📊 정밀도 (Precision): {precision:.4f}")
print(f"📊 재현율 (Recall): {recall:.4f}")
print(f"📊 F1 점수 (F1-score): {f1:.4f}")

# 상세 분류 리포트
print("\n📋 [분류 리포트]")
print(classification_report(y_test, y_pred, target_names=le_label.classes_, zero_division=0))

# confusion matrix (옵션)
cm = confusion_matrix(y_test, y_pred)
print("\n🧩 Confusion Matrix:")
print(cm)




### FastAPi 서버

class RecommendationRequest(BaseModel):
    balance_score_left: int
    balance_score_right: int
    age: int
    gender: int
    condition: str
    recent_scores: list[int]
    recent_intensity_avg: float
    recent_duration_sum: int
    focus_area: str

@router.post("/api/recommend")
def recommend(req: RecommendationRequest):
    condition_map = {"나쁨": 0, "보통": 1, "좋음": 2}
    focus_area_map = {"하체": 0, "코어": 1, "전신": 2, "유연성": 3, "균형": 4}

    condition_encoded = condition_map.get(req.condition, 1)
    focus_area_code = focus_area_map.get(req.focus_area, 2)

    balance_diff = req.balance_score_left - req.balance_score_right
    recent_avg = np.mean(req.recent_scores)
    recent_var = np.var(req.recent_scores)

    X_input = pd.DataFrame([[
        req.balance_score_left, req.balance_score_right, req.age, req.gender,
        condition_encoded, balance_diff, recent_avg, recent_var,
        req.recent_intensity_avg, req.recent_duration_sum, focus_area_code
    ]], columns=X.columns)

    probs = model.predict_proba(X_input)[0]
    top3 = probs.argsort()[-3:][::-1]
    return {
        "status": "success",
        "recommendations": [{"name": le_label.inverse_transform([i])[0]} for i in top3]
    }



#Popular 운동
classes = [
    "의자 스쿼트", "발끝 들기", "뒤꿈치 들기", "버드독", "벽 짚고 플랭크",
    "사이드 스텝", "서서 하는 트위스트", "스탠딩 사이드 레그 리프트",
    "스탠딩 힙 익스텐션", "싱글 레그 스텐딩", "어깨 스트레칭",
    "제자리 걷기", "종아리 스트레칭", "좌우 스텐딩 크런치", "허리 회전 스트레칭"
]

label_rules = {
    "의자 스쿼트": {"score": (40, 60), "age": (65, 80)},
    "발끝 들기": {"score": (30, 50), "age": (70, 80)},
    "뒤꿈치 들기": {"score": (40, 55), "age": (65, 80)},
    "버드독": {"score": (75, 90), "age": (50, 65)},
    "벽 짚고 플랭크": {"score": (80, 95), "age": (50, 60)},
    "사이드 스텝": {"score": (60, 80), "age": (55, 70)},
    "서서 하는 트위스트": {"score": (50, 70), "age": (60, 75)},
    "스탠딩 사이드 레그 리프트": {"score": (45, 65), "age": (50, 70)},
    "스탠딩 힙 익스텐션": {"score": (45, 65), "age": (55, 75)},
    "싱글 레그 스텐딩": {"score": (85, 100), "age": (50, 60)},
    "어깨 스트레칭": {"score": (30, 50), "age": (65, 80)},
    "제자리 걷기": {"score": (50, 65), "age": (60, 75)},
    "종아리 스트레칭": {"score": (40, 55), "age": (65, 80)},
    "좌우 스텐딩 크런치": {"score": (55, 75), "age": (55, 70)},
    "허리 회전 스트레칭": {"score": (45, 65), "age": (65, 80)}
}

class PopularRequest(BaseModel):
    id: int
    score: float  # 평균 좌우 점수
    age: int
    gender: int  # 0: 남성, 1: 여성
    recent_scores: List[int]
    recent_intensity_avg: float
    recent_duration_sum: int
    focus_area: str   # 유저가 주로 한 운동 부위
    weeklyWorkoutCount: int
    history: List[str]   #진행했던 운동

def generate_users(n=150):
    data = []
    for i in range(n):
        label = random.choice(classes)
        rule = label_rules[label]
        age = random.randint(*rule["age"])
        score = random.uniform(*rule["score"])
        gender = random.choice([0, 1])  # int로 바꿔야 함

        count = random.randint(1, 5)
        data.append({
            "id": i,
            "age": age,
            "gender": gender,
            "balanceScore": score,
            "weeklyWorkoutCount": count,
            "history": [label]
        })
    return data

@router.post("/api/ai/popular")
def get_popular(req: PopularRequest):
    print("📥 인기 운동 요청 받음:", req.dict())
    users = generate_users()


    users.append({
    "id": req.id,
    "age": req.age,
    "gender": req.gender,
    "balanceScore": req.score,
    "weeklyWorkoutCount": req.weeklyWorkoutCount,
    "history": req.history,         # ✅ 추가
    "focus_area": req.focus_area,   # (혹시 쓸 수도 있으니 같이 추가)
})




    df = pd.DataFrame(users)
    features = df[["age", "gender", "balanceScore", "weeklyWorkoutCount"]]

    kmeans = KMeans(n_clusters=4, random_state=42).fit(features)
    df["cluster"] = kmeans.labels_

    my_cluster = df[df["id"] == req.id]["cluster"].values[0]
    same = df[df["cluster"] == my_cluster]

    all_focus_areas = []
    for h in same["history"]:
        all_focus_areas.extend(h)

    top = Counter(all_focus_areas).most_common(3)
    return {
        "status": "success",
        "cluster": int(my_cluster),
        "popularExercises": [{"name": name, "count": count} for name, count in top]
    }


#Projection


class ProjectionRequest(BaseModel):
    recentScores: List[int]


@router.post("/api/ai/projection")
async def predict_future_scores(data: ProjectionRequest):
    try:
        recent_scores = data.recentScores

        print("📥 projection 요청 받음:", recent_scores)

        if not recent_scores:
            return {"status": "error", "message": "recentScores 리스트가 필요합니다."}

        prompt = f"""
당신은 운동 균형 점수를 예측하는 AI입니다.
아래는 사용자의 최근 점수입니다 (주 1회 측정 기준): {recent_scores}

이 데이터를 바탕으로 향후 3주간의 예상 점수를 예측해주세요.
점수 범위는 0부터 100까지입니다.
사용자가 운동을 성실히 수행한다고 가정하세요.

다음과 같은 형식의 JSON으로 응답해주세요:
{{
  "week1": float,
  "week2": float,
  "week3": float,
  "comment": "간단한 예측 코멘트 (예: 꾸준한 훈련 시 3~4점 향상이 기대됩니다)"
}}
        """

        response = client.chat.completions.create(
            model="gpt-4",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.6,
            max_tokens=300,
        )

        raw_text = response.choices[0].message.content.strip()
        print("🧠 GPT 응답 원문:", raw_text)

        try:
            result = json.loads(raw_text)
        except json.JSONDecodeError:
            print("❌ JSON 파싱 실패")
            return {
                "status": "error",
                "message": "GPT 응답을 JSON으로 파싱할 수 없습니다.",
                "raw": raw_text
            }

        print("✅ projection 파싱 성공:", result)
        return {"status": "success", "projection": result}

    except Exception as e:
        import traceback
        traceback.print_exc()
        return {"status": "error", "message": str(e)}



#Summary

class SummaryRequest(BaseModel):
    recentScores: List[int]
    leftScore: float
    rightScore: float
    percentile: int
    strongPart: str
    recommendedExercise: str


@router.post("/api/ai/summary")
async def generate_summary(data: SummaryRequest, mode: str = Query(default="natural")):
    try:
        recentScores = data.recentScores
        leftScore = data.leftScore
        rightScore = data.rightScore
        percentile = data.percentile
        strongPart = data.strongPart
        recommendedExercise = data.recommendedExercise

        if not recentScores or not isinstance(recentScores, list):
            return {"status": "error", "message": "recentScores가 비어있거나 잘못됨"}

        # ✅ 프롬프트 분기 처리
        if mode == "list":
            prompt = f'''
당신은 건강 앱의 요약 AI입니다.

다음 정보를 항목별로 요약해주세요 (각 항목은 줄바꿈으로 구분):

- 최근 점수 평균: {sum(recentScores)//len(recentScores)}점
- 또래 대비: 상위 {percentile}%
- 왼발 점수: {leftScore}점
- 오른발 점수: {rightScore}점
- 현재 분석 요약: {"왼발" if leftScore > rightScore else "오른발"} 균형이 더 뛰어납니다.
- 추천 운동: {recommendedExercise}
            '''.strip()
        else:
            prompt = f'''
당신은 건강 앱의 종합 분석 AI입니다.
사용자의 정보는 다음과 같습니다:

- 최근 균형 점수: {recentScores}
- 왼발 점수: {leftScore}
- 오른발 점수: {rightScore}
- 또래 대비 상위 {percentile}%
- 현재 강점: {strongPart}
- 현재 추천 운동: {recommendedExercise}

이 정보를 바탕으로 사용자에게 자연스럽고 격려되는 요약문을 3줄 이내로 작성해주세요.
            '''.strip()

        response = client.chat.completions.create(
            model="gpt-4",
            messages=[
                {"role": "system", "content": "너는 건강 데이터를 요약하는 분석가야"},
                {"role": "user", "content": prompt}
            ],
            temperature=0.7,
            max_tokens=300,
        )

        summary = response.choices[0].message.content
        print("✅ summary 생성 완료")
        return {"status": "success", "summary": summary}

    except Exception as e:
        import traceback
        traceback.print_exc()
        return {"status": "error", "message": str(e)}


app.include_router(router)


# ✅ Step 4. FastAPI 서버 실행
def run_server():
    uvicorn.run(app, host="0.0.0.0", port=8008)

thread = threading.Thread(target=run_server)
thread.start()


# ✅ Step 5. Public URL 노출 (ngrok 사용)
public_url = ngrok.connect(8008)
print(f"🚀 Public API URL: {public_url}")

"""15일 23:29 테스트
api/popular 작동 x
api/summary 작동 x

"""
